---
- name: Update the /etc/hosts with internal network
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/hosts"
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['project_internal_ip'] }} {{ hostvars[item]['project_hostname'] }}"
    state: present
  loop: "{{ groups[application_name] }}"
  when: project_hostname != hostvars[item]['project_hostname']
