---
- name: App role tasks
  module_defaults:
    ansible.builtin.copy:
      backup: true
    ansible.builtin.lineinfile:
      backup: true
    ansible.builtin.xml:
      backup: true
    ansible.builtin.apt:
      cache_valid_time: 86400 # one day
  block:
    - name: Setup users
      ansible.builtin.import_tasks: users.yml
    - name: Setup ruby
      ansible.builtin.import_tasks: ruby.yml
    - name: Setup application
      ansible.builtin.import_tasks: app.yml
    - name: Setup web server
      ansible.builtin.import_tasks: web.yml
