---
- module_defaults:
    ansible.builtin.copy:
      backup: true
    ansible.builtin.lineinfile:
      backup: true
    ansible.builtin.xml:
      backup: true
    ansible.builtin.apt:
      cache_valid_time: 86400 # one day
#  vars:
#    ansible_common_remote_group: ansible
  block:
  - name: Update packages
    ansible.builtin.import_tasks: update.yml
  - name: Setup prereqs
    ansible.builtin.import_tasks: prereqs.yml
  - name: Setup users
    ansible.builtin.import_tasks: users.yml
  - name: Setup ruby
    ansible.builtin.import_tasks: ruby.yml
  - name: Setup application
    ansible.builtin.import_tasks: app.yml
  - name: Cleanup packages
    ansible.builtin.import_tasks: cleanup.yml
